// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarSM.Repositories.VienTLN.Models;

public partial class OrderVienTln
{
    public long OrderVienTlnid { get; set; }

    public long DealerId { get; set; }

    public long? CustomerId { get; set; }

    public long VehicleId { get; set; }

    public int Quantity { get; set; }

    public long? QuoteId { get; set; }

    public long? SalesContractId { get; set; }

    public string OrderType { get; set; }

    public string Status { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal? DiscountPrice { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? IsRefunded { get; set; }

    public virtual ICollection<PaymentVienTln> PaymentVienTlns { get; set; } = new List<PaymentVienTln>();
}