// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarSM.Repositories.VienTLN.Models;

public partial class PaymentVienTln
{
    public long PaymentVienTlnid { get; set; }

    public long OrderId { get; set; }

    public DateTime? PaymentDate { get; set; }

    public decimal AmountPaid { get; set; }

    public string PaymentMethod { get; set; }

    public string TransactionRef { get; set; }

    public string Note { get; set; }

    public string PaymentStatus { get; set; }

    public bool? IsFinalPayment { get; set; }

    public DateTime? ConfirmDate { get; set; }

    public string BankCode { get; set; }

    public virtual OrderVienTln Order { get; set; }
}